project:
  type: website
  output-dir: docs

website:
  title: ""

  navbar:
    logo: "files/LogoNoText.png"
    right:
      - href: index.qmd
        text: About Naomi
      - href: projects.qmd
        text: Latest research
      - href: opensci.qmd
        text: Open science
      - href: news.qmd
        text: In the news
      - href: cv.qmd
        text: CV
      - href: publications.qmd
        text: Publications and outputs
      - href: talks.qmd
        text: Talks
      - href: teaching.qmd
        text: Teaching and supervision
      - href: outreach.qmd
        text: Science club

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

