---
title: "In the news"
html:
  css: styles.css
toc: false
---

Highlights of my current and past research from other sources.

## January 2026

[Here's a blog I wrote for the UK Longitudinal Linkage Collaboration](https://ukllc.ac.uk/blog/2026/01/29/who-gets-screened-linking-data-to-better-understand-cholesterol-screening-in-people-with-mental-illness.html) on using their platform of linked cohort and medical record data. We're trying to determine whether we can use this data to look at access to NHS health screening programmes for people with severe or complex mental illness as part of my Health Data Research UK (HDR UK) fellowship.It's proving challenging due to small numbers of individuals across many cohort studies, and concerns about whether these individuals are representatives of those with mental health conditions. But, it's a fantastically rich resource and hopefully this work will be a first step in saying a bit more about who with mental illness attends screening.

## January 2026

[A great write up](https://www.nationalelfservice.net/other-health-conditions/cardiovascular-disease/cardiovascular-screening-severe-mental-illness/) by the Mental Elf team of our recent paper on the gaps in physical health screening for people with severe mental illness.

## November 2025

[A write up of a great study](https://www.nationalelfservice.net/treatment/antipsychotics/start-metformin-whenever-start-antipsychotics/) by Luiza Farache Trajano looking at the co-prescription of metformin and antipsychotics in people with severe mental illness.

## October 2025

Watch my [invited talk](https://media.ed.ac.uk/media/Epidemiology+Research+Group+seminar+-+Dr+Naomi+Launders+-+8th+Oct+2025/1_chfi2qit) at the Usher Institute, University of Edinburgh.

## September 2025

The [National Academy for Social Prescribing](https://socialprescribingacademy.org.uk/resources/new-study-tracks-five-years-of-social-prescribing-growth/) covered our study on social prescribing uptake, led by Feifei Bu and Alex Burton.

## July 2025

Read about the latest data approvals for my fellowship project through the [British Heart Foundation Data Science centre](https://bhfdatasciencecentre.org/projects/ccu099/).

Read about the first data approvals for my fellowship through the [UK Longitudinal Linkage Collaboration](https://ukllc.ac.uk/data-use-register/the-role-of-sociodemographic-factors-in-attendance-at-cancer-and-cardiovascular-disease-screening-and-in-delayed-cancer-diagnosis-before-during-and-after-the-covid-19-pandemic-in-people-with-severe-o).

## June 2025

[Health Improvement Scotland used our work](https://www.hisengage.scot/media/zaqlhgef/20260626-rethinking-unscheduled-care-insights-for-decision-makers-causal-link-evidence-v1.pdf) on the timing of physical health diagnoses and mental health diagnoses in an evidence report on the burden of unscheduled care

## May 2025

[Review of the Datamind/MQ ECR meeting](https://datamind.org.uk/unlocking-research-insights/), including my presentation on data harmonisation.

## May 2025

The [Australian Institute of Health and Welfare](https://www.aihw.gov.au/mental-health/topic-areas/health-wellbeing/physical-health) referenced my work on severe mental illness and cancer in their report on the physical health of people with severe mental illness.

## April 2025

Our systematic review on physical health hospitalisations in people with severe mental illness was featured in a [UK Parliamentary horizon scanning report](https://post.parliament.uk/mental-health-prevention-and-resilience/) on improving mental health and resilience. The report asked "Mental ill health is on the rise and costs the UK economy billions of pounds every year. How can policymakers support psychological wellbeing and build resilience in England?"

## December 2024

Our research into multimorbidity in people with severe mental illness was referenced in [The Big Mental Health Report by MIND](https://www.mind.org.uk/media/vbbdclpi/the-big-mental-health-report-2024-mind.pdf).

## October 2024

I authored a blog piece for the DATAMIND website: [A Researcher's Journey: How DATAMIND is Transforming Mental Health Research](https://datamind.org.uk/a-researchers-journey-how-datamind-is-transforming-mental-health-research/)

## September 2024

I was an invited speaker at [Personalised Care Week](https://www.personalisedcareinstitute.org.uk/2024/09/11/personalised-care-week/), where the theme was: The Multimorbidity Challenge: A Personalised Care Approach.

## May 2024

HDR UK article on the Big Data for Complex Disease fellowship programme: [Ambitious “rising stars” programme to explore cardiovascular disease, cancer and other complex conditions](https://www.hdruk.ac.uk/news/ambitious-rising-stars-programme-to-explore-cardiovascular-disease-cancer-and-other-complex-conditions/)

## April 2024

[The International Foundation for Integrated Care quoted our work](https://integratedcarefoundation.org/events/ific-webinar-integrated-care-for-people-living-with-long-term-mental-health-conditions) on unplanned physical health hospital admissions for people with severe mental illness in a webinar on integrated care for people with long term mental health conditions.

## November 2023

Evidence from our systematic review on physical health hospitalisations in people with severe mental illness was used by the International Primary Care Respiratory Group to inform targeted recommendations on COPD diagnosis and treatment for people with severe mental illness

## January 2023

[Mental Elf blog](https://www.nationalelfservice.net/other-health-conditions/comorbidity/severe-mental-illness-and-comorbid-chronic-physical-illness-the-clocks-ticking/) on our paper looking at severe mental illness and chronic physical health conditions.

## September 2022

[A Lancet Psychiatry editorial](https://www.thelancet.com/journals/lanpsy/article/PIIS2215-0366(22)00276-0/fulltext) on our paper looking at the timing of physical health diagnoses in people with severe mental illness.
