---
title: "Talks and presentations"
html:
  css: styles.css
toc: false
---

Here is a list of some of the recent talks and presentations I have given on my work.

+---------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+
| **Institution**                                                                 | **Title**                                                                                                                                                          | **Event**                                                                                                                                                                                               | **Date**              |
+---------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+
| UK LLC                                                                          | A researcher view of using UK LLC to investigate cervical screening in people with mental illness                                                                  | UK Longitudinal Linkage Collaboration - a simpler, faster solution to use linked data for research                                                                                                      | 10th June 2026        |
+---------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+
| HDR UK                                                                          | Chair: Data Asset Showcase                                                                                                                                         | Big Data for Complex Disease driver meeting                                                                                                                                                             | 8th May 2026          |
+---------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+
| Swansea University                                                              | Cardiovascular disease and severe mental illness                                                                                                                   | Seminar on mental health and cardiovascular disease                                                                                                                                                     | 19th March 2026       |
+---------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+
| Health Data Research UK                                                         | Translating Health Data Research into Public Health Action                                                                                                         | ECR Elevate seminar series                                                                                                                                                                              | 19th November 2025    |
+---------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+
| Mental Health Platform                                                          | Attempting to pick apart mechanisms of action of statins using electronic health records and target trial emulation                                                | Mental Health Platform Research Summit                                                                                                                                                                  | 10th October 2025     |
+---------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+
| University of Edinburgh                                                         | Investigating cardiovascular disease and cancer using electronic health records                                                                                    | Seminar series                                                                                                                                                                                          | 8th October 2025      |
+---------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+
| KaBris                                                                          | Using longitudinal cohort data linked to cohort data to investigate cancer and cardiovascular disease screening and diagnosis in people with severe mental illness | KaBris conference                                                                                                                                                                                       | 11th September 2025   |
+---------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+
| HDR UK                                                                          | Health inequalities in cardiovascular disease and cancer in people with severe or complex mental illness                                                           | HDR UK funding meeting                                                                                                                                                                                  | 21^st^ January 2025   |
+---------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+
| Personalised Care Institute                                                     | The burden of physical long-term conditions in people with severe mental illness: what medical records tell us                                                     | Personalised Care Week, 2024                                                                                                                                                                            | 23^rd^ September 2024 |
+---------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+
| Royal College of Psychiatrists                                                  | Patterns and timing of physical health diagnoses in people with severe mental illness and the implications for policy                                              | Symposium at the International Congress: Severe mental illness: moving the needle on health inequalities and premature mortality. New national findings regarding multimorbidity, diabetes and Covid-19 | 17th June 2024        |
+---------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+
| University of Edinburgh                                                         | 1.  Cardiovascular risk screening in people with severe mental illness across the UK                                                                               | SMI and Physical Disease mini-conference, 2024                                                                                                                                                          | 29^th^ February 2024  |
|                                                                                 | 2.  Using routine data for mental health research: strengths and challenges                                                                                        |                                                                                                                                                                                                         |                       |
+---------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+
| Cardiff University                                                              | Studying the physical health of people with severe mental illness using electronic health records                                                                  | Distinguished speaker seminar series                                                                                                                                                                    | 17^th^ January 2024   |
+---------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+
| NHS England                                                                     | The physical health and related hospital use in people with severe mental illness                                                                                  | Physical Health of SMI regional forum                                                                                                                                                                   | 1^st^ March 2023      |
+---------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+
| European Psychiatric Association: Section of Epidemiology and Social Psychiatry | Clustering and accumulated prevalence of physical health conditions in people with and without severe mental illness                                               | Symposium at the section congress: Challenges and opportunities in mental health data science: the DATAMIND experience                                                                                  | 10^th^ September 2022 |
+---------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+
| Office for Health Improvement and Disparities                                   | Hospital admissions in people with severe mental illness                                                                                                           | Senior Analysts Forum, National Mental Health Intelligence Network                                                                                                                                      | 2^nd^ December 2021   |
+---------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+
