---
title: "Teaching and supervision"
html:
  css: styles.css
toc: false
---

# Teaching

## UCL

I regularly teach epidemiology and statistics on the UCL MSc in Clinical Mental Health Sciences and MSc in Mental Health Sciences Research. I am co-deputy lead of the MSc module Epidemiology Research Methods in Mental Health (PSBS0013) and teach statistics on the Core Principals of Mental Health Research MSc module (PSBS0002).

I am also a committee member for the UCL Clinical Data Science Technology Platform training where I have co-designed and taught on a series of workshops on using primary care databases for research at UCL.

## Other universities

I guest lecture on the MSc in Mental Health Research at the University of Sussex where I teach medical records research.

## Workshops

In 2023 I co-designed and taught on a one-day workshop on using R for epidemiological research in collaboration with MQ and DATAMIND. Recordings of the day can be found [here](https://datamind.org.uk/epidemiological-methods-for-mental-health-research-using-r-workshop/). In 2025, I returned to the event to present a lecture on data harmonisation.

# Examining research students

I have acted as an external examiner for PhD theses at other universities in the UK, and as upgrade examiner for PhD students at UCL. I am always open to offers to examine PhD theses on topics of epidemiology, data science, mental health and physical health.

# Supervision

I am open to new PhD students who wish to work with electronic health records and have an interest in the interplay of physical and mental health. Please [email me](mailto:naomi.launders@ucl.ac.uk) if you'd like to discuss opportunities.

## Current students

::: tight
### PhD supervision:

**Anna Tsaligopoulou:** Employing Machine Learning (ML) to Better Predict the Development of Mental Health Problems in Adolescence: A biosocial approach. January 2025 – present: secondary supervisor

**Yehudit Bauernfreund:** Investigating inequalities in delirium detection and outcomes for people with severe mental illness: understanding current practice, clinical challenges and opportunities for change. September 2025 - present: external supervisor (Queen Marys University London)

**Oliver Kelsey:** Dementia care for people with serious mental illness. September 2025 - present: external supervisor (Queen Marys University London)

### PhD thesis committee:

**Alua Yeskendir:** Ethnic and migration variation and impact of acculturation and socioeconomic deprivation on the incidence of severe mental illness, self-harm, and suicide. May 2024 – present:

### MSc supervision

**Umut Sadet:** Systematic review of the relationship between heart failure and mental health and the impact on heart failure treatment and mortality. January 2026 – present: primary supervisor

**Aisling O’Neill:** The physical health of people with personality disorder: A systematic review. January 2026 – present: primary supervisor
:::

## Past students

::: tight
### PhD thesis committee:

**Alvin Richards-Belle:** Cardiometabolic safety and effectiveness of frequently prescribed antipsychotics in severe mental illness. January 2023 – December 2025

### MSc supervision:

**Thea Nelson:** Variations in Special Educational Needs and Disabilities (SEND) Support and Educational Outcomes by Local and Unitary Authority: A Longitudinal Ecological Study. January 2025-September 2025: Secondary supervisor

**Hanzhang Wang:** Common Mental Disorders, Self-harm and Suicide: A cohort study using England primary care data. January 2024-September 2024: Secondary supervisor.

**Shruti Menon:** Risk factors of Suicide and Self-harm in people with Autism-Spectrum Disorder and Attention-Deficit Hyperactivity Disorder in England: A cohort study in primary care. January 2024-September 2024: Secondary supervisor:

**Yehudit Bauernfreund:** Risk and mortality of hospital delirium in people with pre-existing severe mental illness: a data linkage study. January 2023-September 2023: Secondary supervisor

**Leiah Kirsh:** Chronic Comorbidity and Multimorbidity in Patients with Severe Mental Illness: A 10-year Follow-Up of Disease Burden. January 2021-September 2021: Secondary supervisor:

### BSc supervision:

**Jasmine Little:** The Relationship between Depression and Coronary Heart Disease through a Biopsychosocial Approach: An Umbrella Systematic Review. October 2023-August 2024: Primary supervisor

### Clinical Academic Foundation year one rotation supervision:

**Ella Burchill:** The temporal relationship between severe mental illness and neurological conditions in a UK primary care cohort. August 2023-November 2023: Secondary supervisor
:::

# Mentorship

I currently mentor one PhD student in UCL, and one through the HDR UK mentorship programme. I have a mentor myself through the HDR UK programme. I am always open to discussing mentorship opportunities and other ways of collaborative working.
